
#Crazy AE2 Addons - Config
[general]
	#Enables The functionality of pattern providers to set the circuit of the GregTech's machine its pushing to
	enableCPP = true
	#Enables Spawner Controller to work also on peacefull mode
	enablePeacefullSpawner = true
	#Enables/disables the entity ticker
	enableEntityTicker = true
	#You can set the power cost multiplayer for the entity ticker here
	#Range: 0 ~ 4096
	EntityTickerCost = 256
	#Blocks on which entity ticker should not work
	EntityTickerBlackList = []
	#If it should be possible to route p2p tunnels through a wormhole tunnel
	nestedP2Pwormhole = false

