# 开启永恒蓝梦和蓝梦主机合成表的注册，注意这可能会影响游戏平衡（修改后请退出重进）
enableInfinityDreamAndDreamHostCrafting: false

# 开启黑洞物质解压器实体渲染,当延迟过大时关闭此项
enableBlackHoleMatterDecompressor: true

# 开启超维度发电机实体渲染,当延迟过大时关闭此项
enableHyperDimensionalPower: true

# 开启通用蒸汽机（修改后请退出重进）
enableGeneralPurposeSteamEngine: false

# 开启通用AE制造机（修改后请退出重进）
enableGeneralAEManufacturingMachine: false

