disableDrift: true

enableSkyBlokeMode: true

oreMultiplier: 4

cellType: 4

spacetimePip: 2147483647

durationMultiplier: 0.05

travelStaffCD: 2

# 更大的数值会让界面显示有问题，推荐在样板管理终端管理
exPatternProvider: 72

enablePrimitiveVoidOre: true

# 连锁黑名单,支持通配符*
blackBlockList:
  - ae2:cable_bus
  - minecraft:grass_block

mobList1:
  - chicken
  - rabbit
  - sheep
  - cow
  - horse
  - pig
  - donkey
  - skeleton_horse
  - iron_golem
  - wolf
  - goat
  - parrot
  - camel
  - cat
  - fox
  - llama
  - panda
  - polar_bear

mobList2:
  - ghast
  - zombie
  - pillager
  - zombie_villager
  - skeleton
  - drowned
  - witch
  - spider
  - creeper
  - husk
  - wither_skeleton
  - blaze
  - zombified_piglin
  - slime
  - vindicator
  - enderman

